### ISSUE TITLE
[Information] BLE Light Mesh

### ISSUE THREAD

**Issue by Minims** [cmorriss/ble-mesh-hub#1]
Hello, 

Do you plan to control bee mesh light with No OOB with this hub on ESP32 ? 

Thanks

**Comment by cmorriss** [comment]
Hi, Sorry, just saw this. I'm not sure I understand the question. What do you mean by "No OOB"? Note that this is a completely different implementation of a mesh framework from the standard BLE mesh. I primarily put it out there as something interesting that others could either learn from or use in another project. I'm not maintaining it in any way.

All that being said, I'm happy to answer any questions or give more details on it.

**Comment by Minims** [comment]
Hello,

I have 2 BLE mesh light. While provisioning them I need to set "No OOB" instead of "Static OOB" to make them work with my phone application.

**Comment by cmorriss** [comment]
I think this is related to the BLE mesh standard, which this code does not work with. I'm not super familiar with the details of the normal BLE mesh implementation and thus won't be able to help.
